---
- name: Compliance check for critical services
  hosts: all
  become: yes

  vars:
    critical_services:
      - sshd.service
      - firewalld.service
      - docker.service

  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Check compliance for critical services
      vars:
        svc_state: "{{ ansible_facts.services[item] | default({'state': 'not installed', 'status': 'not installed'}) }}"
      debug:
        msg: >
          Service {{ item }} is {{ svc_state.state }} and {{ svc_state.status }} on {{ inventory_hostname }}
      loop: "{{ critical_services }}"

    - name: Fail if a critical service is not running
      ansible.builtin.fail:
        msg: "Critical service {{ item }} is NOT running on {{ inventory_hostname }}"
      loop: "{{ critical_services }}"
      when: ansible_facts.services[item].state is defined and ansible_facts.services[item].state != "running"

    - name: Record compliance stats
      ansible.builtin.set_stats:
        data:
          compliance_results: "{{ hostvars[inventory_hostname]['ansible_facts']['services'] }}"

